import os
import json
from dotenv import load_dotenv
from groq import Groq
load_dotenv()
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


def llm_signal(text: str) -> dict:
    """
    Signal 1: ask an LLM to judge whether text reads as AI-generated or
    human-written. Returns a score 0-1 where 1.0 = strongly AI-like.

    Captures: holistic semantic/stylistic coherence.
    Blind spot: black-box judgment, can be fooled by short or
    very formal human text, no visibility into *why* it scored this way.
    """
    prompt = f"""You are analyzing a piece of text to judge whether it was likely written by a human or generated by an AI language model.

Consider sentence rhythm, word choice specificity, presence of genuine idiosyncrasy or imperfection, and overall naturalness.

Respond ONLY with valid JSON in this exact format, no other text:
{{"ai_score": <float between 0.0 and 1.0, where 1.0 means strongly AI-generated and 0.0 means strongly human-written>, "reasoning": "<one sentence explanation>"}}

Text to analyze:
\"\"\"{text}\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
    )

    raw = response.choices[0].message.content.strip()

    try:
        parsed = json.loads(raw)
        score = float(parsed["ai_score"])
        reasoning = parsed.get("reasoning", "")
    except (json.JSONDecodeError, KeyError, ValueError):
        # Fallback if the model doesn't return clean JSON
        score = 0.5
        reasoning = "Could not parse model output; defaulted to uncertain."

    score = max(0.0, min(1.0, score))  # clamp to [0,1] in case model misbehaves

    return {"score": score, "reasoning": reasoning}